### ISSUE TITLE
Support YAML Multi Documents (in one file)

### ISSUE THREAD

**Issue by jacobsvante** [juliojimenez/yamler#120]
Currently yamler returns the following error: `This just happened: Source contains multiple documents; please use YAML.parseAllDocuments()`.

Example file that should give this error:

```yaml
document: this is document 1
---
document: this is document 2
```

Perhaps if there's multiple documents each variable could be prefixed by "docX__" so the result for above would be:

```
doc1__document
doc2__document
```
